# list of input file paths
include:
  - ./path/to/input/file0.lang
  - ./path/to/input/file1.lang

# output directory path
output: ./out

# default tag if no other tags are defined in the document
fallback-tag: out

# changes the output structure of the parser
# options:
#
# 'one-lang-per-file' (default):
# each language in the project gets compiled to its own file
# ex. language.json->tag->key->value
#
# 'one-tag-per-file':
# each tag in the project gets compiled to its own file
# ex. tag.json->language->key->value
output-structure: one-lang-per-file

# define the syntax for the parser
COMMENT: '#'
INDENT: ' '
NEW_LINE: '\n'
OPEN_DEF: ':'
END_DEF: 'end'
OPEN_TAG: '['
CLOSE_TAG: ']'
SEP: '---'
